version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://nexus.adaptris.net/nexus/content/groups/interlok
    username: dummy
    password: dummy-since-this-is-a-public-repo

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    target-branch: "release"
    allow:
      - dependency-type: "all"
    labels:
      - "github_actions"
      - "release"
    reviewers:
      - aaron-mcgrath-adp
      - sebastien-belin-adp
      - higgyfella

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    target-branch: "release-v4"
    allow:
      - dependency-type: "all"
    labels:
      - "github_actions"
      - "release-v4"
    reviewers:
      - aaron-mcgrath-adp
      - sebastien-belin-adp
      - higgyfella
