name: Docker Publish

on:
  push:
    branches:
      - snapshot
    # A tag will build and publish the Docker images
    tags: [ '*.*.*' ]
  pull_request:
    branches: [ "snapshot" ]

jobs:
  build-and-push:
    strategy:
      matrix:
        dist: [corretto, debian, zulu, zulu-alpine, adoptopenjdk, msopenjdk]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Tags
        id: get-tags
        uses: actions/github-script@v6
        with:
          script: |
            function buildFullTag(tag) {
              return "adaptris/interlok:" + tag + "-${{ matrix.dist }}";
            }
            var artifactAndTags = [];
            var tag = "snapshot";
            if ('${{ github.ref_type }}' == 'tag') {
              tag = "${{ github.ref_name }}";
              artifactAndTags.push(buildFullTag("latest"));
            }
            artifactAndTags.push(buildFullTag(tag));
            return {tag: tag, artifactAndTags: artifactAndTags.join(",")}
          result-encoding: json

      - name: Echo
        run: |
          echo "Build Docker image: ${{ fromJson(steps.get-tags.outputs.result).artifactAndTags }}, Tag: ${{ fromJson(steps.get-tags.outputs.result).tag }}, Publish: ${{ github.event_name != 'pull_request' }}"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: ./${{ matrix.dist }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ fromJson(steps.get-tags.outputs.result).artifactAndTags }}
          labels: interlok
          build-args: INTERLOK_BASE_IMAGE=${{ fromJson(steps.get-tags.outputs.result).tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
